services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        # DATABASE_URL: ${DATABASE_URL}  # Uncomment and set if using database
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # - DATABASE_URL=${DATABASE_URL}  # Uncomment and set if using database
    restart: unless-stopped
    container_name: testbhvr-app
    # Optional: Add health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
