services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        # DATABASE_URL: ${DATABASE_URL}  # Uncomment and set if using database
    ports:
      - "5173:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: testbhvr-app
   
    
networks:
  dokploy-network:
    external: true
